version: "3"

x-service-defaults: &service-defaults
  build:
    context: .
  ports:
    - "3000:3000"
  volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
  depends_on:
    db:
      condition: service_healthy

services:
  dev:
    <<: *service-defaults
    container_name: mrs-api-dev
    command: npm run start:docker
    environment:
      - PORT=3000
      - NODE_ENV=dev
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dev_db?schema=public

    networks:
      default:
        aliases:
          - mrs-net-dev

  test:
    <<: *service-defaults
    container_name: mrs-api-test
    command: sh -c "npm run migrate:dev && npm run test"
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/test_db?schema=public

    networks:
      default:
        aliases:
          - mrs-net-test

  db:
    container_name: mrs-db
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5405:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      default:
        aliases:
          - mrs-net-db

networks:
  default:
    name: mrs-net
