components:
  schemas:
    Movie:
      type: object
      required:
        - title
        - description
        - posterUrl
        - genreId
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique identifier (uuidv4).
          example: "5096104f-68c4-4a07-983a-2a1e47e32f79"
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: Required. 255 characters or fewer.
          example: Matrix
        description:
          type: string
          minLength: 1
          maxLength: 100
          description: Required. 255 characters or fewer.
          example: A computer hacker investigates the parallels between the Matrix and the real world.
        posterUrl:
          type: string
          format: url
          description: Required. URL of the poster image.
          example: "https://image.tmdb.org/t/p/w500/u2y0x7j0l3o0p3n0j3u7.jpg"
        genreId:
          type: string
          description: Required. Foreign key to the genre of the movie.
          example: "5096104f-68c4-4a07-983a-2a1e47e32f79"
