components:
  schemas:
    Room:
      type: object
      required:
        - name
        - rows
        - columns
        - baseSeatPrice
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique identifier (uuidv4).
          example: "5096104f-68c4-4a07-983a-2a1e47e32f79"
        name:
          type: string
          minLength: 1
          maxLength: 50
          description: Required. 50 characters or fewer.
          example: Sala 1
        rows:
          type: integer
          description: Required. Number of rows.
          minimum: 0
          maximum: 500
          example: 5
        columns:
          type: integer
          description: Required. Number of columns.
          minimum: 0
          maximum: 500
          example: 3
        baseSeatPrice:
          type: number
          format: double
          multipleOf: 0.01
          description: Required. Base seat price.
          minimum: 0
          example: 10.53
