components:
  schemas:
    Room:
      type: object
      required:
        - name
        - rows
        - columns
        - baseSeatPrice
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: Unique identifier (uuidv4).
          example: "5096104f-68c4-4a07-983a-2a1e47e32f79"
        name:
          type: string
          minLength: 1
          maxLength: 50
          description: Required. 50 characters or fewer.
          example: Sala 1
        number:
          type: integer
          description: Required. Room number.
          minimum: 1
          maximum: 500
          example: 5
