paths:
  /api/v1/showtimes:
    get:
      tags:
        - Showtimes
      description: List showtimes by desc datetime.
      parameters:
        - in: query
          name: date
          required: false
          schema:
            type: string
            format: date
          description: Optional. Date in ISO8601 format.
          example: "2022-01-01"
        - in: query
          name: page
          required: false
          schema:
            type: number
            format: integer
            minimum: 1
          description: Optional. Page number. Default to 1.
          example: 1
        - in: query
          name: perPage
          required: false
          schema:
            type: number
            format: integer
            minimum: 1
            maximum: 10
          description: Optional. Number of items per page. Default to 10.
          example: 10
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PaginationResponse"
                  - type: object
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/Showtime"
        401:
          $ref: "#/components/responses/Unauthorized"
    post:
      tags:
        - Showtimes
      summary: Admin only
      description: Create and return a new showtime.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Showtime"
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Showtime"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/Forbidden"
        400:
          $ref: "#/components/responses/BadRequest"
  /api/v1/showtimes/{id}/available-seats:
    get:
      tags:
        - Showtimes
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier (uuidv4).
          example: "5096104f-68c4-4a07-983a-2a1e47e32f79"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PaginationResponse"
                  - type: object
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/Seat"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
